language: java
jdk:
  - oraclejdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN=854a2397-af6e-4672-8583-50c8ccf01083